spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
